spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: CronoSana
  config:
    import: optional:file:.env[.properties]

  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: create-drop  #update
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  port: ${SERVER_PORT:8080}